### ISSUE TITLE
Multiple upstream DNS servers fail

### ISSUE THREAD

**Issue by ThomasRunting** [lancachenet/docker-compose#10]
adding more then one ipstream dns in the .env file breaks the stack.

192.168.1.3 192.168.1.1
192.168.1.3; 192.168.1.1
192.168.1.3:192.168.1.1

These all broke.

I ended up fixing it by edditing the envioment vaiable in portainer for the dns

**Comment by MathewBurnett** [comment]
I believe the syntax is UPSTREAM_DNS="192.168.1.3; 192.168.1.1"

**Comment by ThomasRunting** [comment]
Nope 
UPSTREAM_DNS="192.168.1.3; 192.168.1.1"
 Wont work

On Lancache_dns
```
checking Bind9 config
/etc/bind/named.conf.options:12: expected IP address near '"'
Problem with Bind9 configuration - Bailing
ERROR: hook /hooks/supervisord-pre.d/10_config_check.sh} returned a non-zero exit status '0'
```
on sniproxy
```
2020-03-09 20:25:51 error parsing /etc/sniproxy.conf at 93 near:
2020-03-09 20:25:51  94	68.1.3; 192.168.1.1"
2020-03-09 20:25:51  110		mode ipv4_only
03-09 20:25:51  112	}
2020-03-09 20:25:51  113
2020-03-09 20:25:51  126	access_log {
Unable to load /etc/sniproxy.conf
Usage: sniproxy [-c <config>] [-f] [-n <max file descriptor limit>] [-V]
```

on monolithic
```
# Finished including /etc/nginx/nginx.conf
Checking nginx config
nginx: [emerg] host not found in resolver "192.168.1.3; 192.168.1.1" in /etc/nginx/sites-available/generic.conf.d/10_generic.conf:1
nginx: configuration file /etc/nginx/nginx.conf test failed
ERROR: hook /hooks/supervisord-pre.d/99_config_check.sh} returned a non-zero exit status '0
```

**Comment by GotenXiao** [comment]
That's annoying, I could've sworn I tested this while working on the refactor and verified it worked as documented.

As a workaround, specify `UPSTREAM_DNS` as space-separated in `.env` - this will enable monolithic and sniproxy to work correctly, and then make the following change to your `docker-compose.yml` for your dns service definition:

```diff
diff --git a/docker-compose.yml b/docker-compose.yml
index 65e6938..ed41a25 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -5,6 +5,8 @@ services:
     env_file: .env
     ports:
       - ${DNS_BIND_IP}:53:53/udp
+    environment:
+      UPSTREAM_DNS: '8.8.8.8; 8.8.4.4'
   sniproxy:
     image: lancachenet/sniproxy:latest
     env_file: .env
```

This will override that setting *just* for the DNS service and allow it to work correctly.

**Comment by ThomasRunting** [comment]
Yes this did fix the issue.

Maybe the documentation needs to be updated with this as well.

Or put another line for the dns in the env file for people that need more then one  upstream dns.

My docker-compose and .env

```
version: '2'
services:
  dns:
    image: lancachenet/lancache-dns:latest
    env_file: .env
    ports:
      - ${DNS_BIND_IP}:53:53/udp
    environment:
     UPSTREAM_DNS: '192.168.1.3; 192.168.1.1'

  sniproxy:
    image: lancachenet/sniproxy:latest
    env_file: .env
    ports:
      - 443:443/tcp
  monolithic:
    image: lancachenet/monolithic:latest
    env_file: .env
    ports:
      - 80:80/tcp
    volumes:
      - ${CACHE_ROOT}/cache:/data/cache
      - ${CACHE_ROOT}/logs:/data/logs
```

```
## See the "Settings" section in README.md for more details

## Set this to true if you're using a load balancer, or set it to false if you're using seperate IPs for each service.
## If you're using monolithic (the default), leave this set to true
USE_GENERIC_CACHE=true

## IP addresses that the lancache monolithic instance is reachable on
## Specify one or more IPs, space separated - these will be used when resolving DNS hostnames through lancachenet-dns. Multiple IPs can improve cache priming performance for some services (e.g. Steam)## IP A$
## Note: This setting only affects DNS, monolithic and sniproxy will still bind to all IPs by default
LANCACHE_IP=192.168.1.136

## IP address on the host that the DNS server should bind to
DNS_BIND_IP=192.168.1.136

## DNS Resolution for forwarded DNS lookups
UPSTREAM_DNS=192.168.1.3 192.168.1.1

## Storage path for the cached data
## Note that by default, this will be a folder relative to the docker-compose.yml file
CACHE_ROOT=/cachedrive

## Change this to customise the size of the memory cache (default 500m)
CACHE_MEM_SIZE=1000m

## Change this to customise the size of the disk cache (default 1000000m)
## If you have more storage, you'll likely want to increase this
## The cache server will prune content on a least-recently-used basis if it
## starts approaching this limit
CACHE_DISK_SIZE=900000m

## Change this to limit the maximum age of cached content (default 3650d)
CACHE_MAX_AGE=3650d
```
