### ISSUE TITLE
Invalid keys on NGINX

### ISSUE THREAD

**Issue by jona8690** [lancachenet/docker-compose#8]
Hi

I'm recieving the following errors when trying to launch the docker-compose.
```
Checking nginx config


nginx: [emerg] invalid keys zone size "keys_zone=generic:5g" in /etc/nginx/conf.d/20_proxy_cache_path.conf:1


nginx: configuration file /etc/nginx/nginx.conf test failed


ERROR: hook /hooks/supervisord-pre.d/99_config_check.sh} returned a non-zero exit status '0'
```
Other than below, everythign is default.

Environmnt is set up like this:
```
## Set this to true if you're using a load balancer, or set it to false if you're using seperate IPs for each service.
USE_GENERIC_CACHE=true

## IP Address that the lancache load balancer will be running on
LANCACHE_IP=10.245.100.176

DNS_IP=10.245.100.175

## DNS Resolution for forwarded DNS lookups
UPSTREAM_DNS=10.245.110.100

## Storage path for the cached data
CACHE_ROOT=/mnt/md0/lancache

## Which type of steam caching to use [generic|steamcache]
STEAMCACHE_CONTAINER=generic

CACHE_MEM_SIZE=5g
CACHE_DISK_SIZE=100g
```

and the network configuration:

```
network:
  version: 2
  renderer: networkd
  ethernets:
    enp3s0f0:
      dhcp4: yes
    enp3s0f1:
      optional: true
    enp4s0f0:
      optional: true
    enp4s0f1:
      optional: true
  bonds:
    bond0:
      interfaces: [enp3s0f0, enp3s0f1, enp4s0f0, enp4s0f1]
      dhcp4: yes
```
